[2023-02-10T23:15:39.929+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-02-08T15:15:00+00:00 [queued]>
[2023-02-10T23:15:39.935+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-02-08T15:15:00+00:00 [queued]>
[2023-02-10T23:15:39.935+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T23:15:39.935+0200] {taskinstance.py:1369} INFO - Starting attempt 1 of 4
[2023-02-10T23:15:39.935+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T23:15:39.940+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-02-08 15:15:00+00:00
[2023-02-10T23:15:39.944+0200] {standard_task_runner.py:52} INFO - Started process 18662 to run task
[2023-02-10T23:15:39.947+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales', 'extract_data_from_api', 'scheduled__2023-02-08T15:15:00+00:00', '--job-id', '1177', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/mainS.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmp1zz4ftn6', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpdxtoaeot']
[2023-02-10T23:15:39.949+0200] {standard_task_runner.py:80} INFO - Job 1177: Subtask extract_data_from_api
[2023-02-10T23:15:39.975+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-02-08T15:15:00+00:00 [running]> on host admins-MacBook-Air-2.local
[2023-02-10T23:15:40.002+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales
AIRFLOW_CTX_TASK_ID=extract_data_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-02-08T15:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-08T15:15:00+00:00
[2023-02-10T23:15:40.331+0200] {python.py:173} INFO - Done. Returned value was: {'data': {'message': 'Authorization token not set properly. You are not authorised to use this resourse'}}
[2023-02-10T23:15:40.359+0200] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=test_process_sales, task_id=extract_data_from_api, execution_date=20230208T151500, start_date=20230210T211539, end_date=20230210T211540
[2023-02-10T23:15:40.410+0200] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10T23:15:40.430+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
