[2023-02-10T22:28:38.940+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T19:15:00+00:00 [queued]>
[2023-02-10T22:28:38.946+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T19:15:00+00:00 [queued]>
[2023-02-10T22:28:38.946+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T22:28:38.946+0200] {taskinstance.py:1369} INFO - Starting attempt 1 of 4
[2023-02-10T22:28:38.946+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T22:28:38.951+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-01-09 19:15:00+00:00
[2023-02-10T22:28:38.956+0200] {standard_task_runner.py:52} INFO - Started process 9491 to run task
[2023-02-10T22:28:38.959+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales', 'extract_data_from_api', 'scheduled__2023-01-09T19:15:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/mainS.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmplvolpylj', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmp6hrfwygj']
[2023-02-10T22:28:38.960+0200] {standard_task_runner.py:80} INFO - Job 254: Subtask extract_data_from_api
[2023-02-10T22:28:43.551+0200] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 9491. PIDs of all processes in the group: [9491]
[2023-02-10T22:28:43.552+0200] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 9491
[2023-02-10T22:28:43.557+0200] {process_utils.py:75} INFO - Process psutil.Process(pid=9491, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='22:28:38') (9491) terminated with exit code Negsignal.SIGTERM
[2023-02-10T22:28:46.418+0200] {taskinstance.py:1161} INFO - Dependencies not met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T19:15:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-02-10T22:28:46.421+0200] {taskinstance.py:1161} INFO - Dependencies not met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T19:15:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-02-10T22:28:46.424+0200] {local_task_job.py:101} INFO - Task is not able to be run
