[2023-02-11T19:16:57.619+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-02-11T14:00:00+00:00 [queued]>
[2023-02-11T19:16:57.628+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-02-11T14:00:00+00:00 [queued]>
[2023-02-11T19:16:57.628+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-11T19:16:57.628+0200] {taskinstance.py:1369} INFO - Starting attempt 2 of 4
[2023-02-11T19:16:57.628+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-11T19:16:57.636+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-02-11 14:00:00+00:00
[2023-02-11T19:16:57.641+0200] {standard_task_runner.py:52} INFO - Started process 41244 to run task
[2023-02-11T19:16:57.646+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales', 'extract_data_from_api', 'scheduled__2023-02-11T14:00:00+00:00', '--job-id', '2833', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/mainS.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpcj0g1dym', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpmln0r6ug']
[2023-02-11T19:16:57.648+0200] {standard_task_runner.py:80} INFO - Job 2833: Subtask extract_data_from_api
[2023-02-11T21:17:13.239+0200] {local_task_job.py:193} ERROR - The recorded hostname 1.0.0.127.in-addr.arpa does not match this instance's hostname 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-02-11T21:17:13.250+0200] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 41244. PIDs of all processes in the group: [41244]
[2023-02-11T21:17:13.250+0200] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 41244
[2023-02-11T21:17:13.252+0200] {process_utils.py:75} INFO - Process psutil.Process(pid=41244, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='19:16:57') (41244) terminated with exit code Negsignal.SIGTERM
