[2023-02-10T23:06:03.869+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T04:00:00+00:00 [queued]>
[2023-02-10T23:06:03.875+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T04:00:00+00:00 [queued]>
[2023-02-10T23:06:03.875+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T23:06:03.875+0200] {taskinstance.py:1369} INFO - Starting attempt 3 of 4
[2023-02-10T23:06:03.875+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T23:06:03.880+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-01-10 04:00:00+00:00
[2023-02-10T23:06:03.884+0200] {standard_task_runner.py:52} INFO - Started process 16145 to run task
[2023-02-10T23:06:03.887+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales', 'extract_data_from_api', 'scheduled__2023-01-10T04:00:00+00:00', '--job-id', '877', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/mainS.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpqs5qap0_', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpsvms6nud']
[2023-02-10T23:06:03.888+0200] {standard_task_runner.py:80} INFO - Job 877: Subtask extract_data_from_api
[2023-02-10T23:06:03.922+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-10T04:00:00+00:00 [running]> on host admins-MacBook-Air-2.local
[2023-02-10T23:06:03.949+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales
AIRFLOW_CTX_TASK_ID=extract_data_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-01-10T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-10T04:00:00+00:00
[2023-02-10T23:06:04.242+0200] {python.py:173} INFO - Done. Returned value was: {'message': 'Authorization token not set properly. You are not authorised to use this resourse'}
[2023-02-10T23:06:04.257+0200] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=test_process_sales, task_id=extract_data_from_api, execution_date=20230110T040000, start_date=20230210T210603, end_date=20230210T210604
[2023-02-10T23:06:04.297+0200] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10T23:06:04.315+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
